[env]
APP_TIMEZONE = "Europe/Berlin"
GOOGLE_WORKSPACE_PROJECT_ID = "rider-499313"
GOOGLE_PROJECT_ID = "rider-499313"
GOOGLE_SERVICE_ACCOUNT_EMAIL = "rider-22@rider-499313.iam.gserviceaccount.com"
GOOGLE_APPLICATION_CREDENTIALS = "/Users/daniel/code/wsc-prototypes/google-service-account.local.json"

CLERK_APP_ID = "app_3F5I0r7ipX4ueR77SHBRhBcJTHw"
CLERK_DEV_INSTANCE_ID = "ins_3F5I0uuy1tbzHFScNL7pnhahpEr"

BETTER_AUTH_URL = "http://localhost:3001"
BETTER_AUTH_DATABASE_URL = "file:./data/better-auth.sqlite"

WSC_DRIVE_ROOT_FOLDER_ID = "1DFcRTGyaknZjzLDhbjFK1_IokboR8-4Z"

WSC_CLERK_DRIVE_FOLDER_ID = "1CTGQDIKhe2nKL6HZMQLxfumIsZcjN0IZ"
WSC_CLERK_SESSIONS_FOLDER_ID = "1K1zgFuWrn7dpXwsXfcf25exrsSUE0hRH"
WSC_CLERK_RIDERS_SPREADSHEET_ID = "1Ybr0wRcsbB97J6lqq7pUpX6UXphc6SAXrC_FRcmc9Ys"
WSC_CLERK_TRAINING_SPREADSHEET_ID = "1jE_FiT83l1OTf_Q3jjr3pIT5SwgLfB9yJCvDxlg0rQQ"

WSC_BETTER_AUTH_DRIVE_FOLDER_ID = "1stSLw6JwxDBWfrNv-HKZCTu5ue2u8Aov"
WSC_BETTER_AUTH_SESSIONS_FOLDER_ID = "1V3iewyflYNF19EZpGgK327MuQWSgff5C"
WSC_BETTER_AUTH_RIDERS_SPREADSHEET_ID = "1rerb0vgAkBi7hStXzvucDDEKUNX7kUYAQpZdlEhPlfo"
WSC_BETTER_AUTH_TRAINING_SPREADSHEET_ID = "1TfQC6LS963vhooZjtMc_wnes3xtUtiFMzKnEpJY_nJg"

SCHEDULER_ENABLED = "false"
SCHEDULER_INTERVAL_CRON = "*/5 * * * *"
